version: '3.7'

services:

  app:
    container_name: gameLab_vue
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '222:8080'
    environment:
      - CHOKIDAR_USEPOLLING=true
